### ISSUE TITLE
Crash fetching fedora packages

### ISSUE THREAD

**Issue by Leoniels** [blalop/pkg-query#1]
Apparently the script crashes when fetching the package version of fedora due to some dependency missing (_chromedriver_).

```bash
niels@Fawkes $ bin/pkg-query gcc
gcc
Arch: 9.1.0-2
Debian stable: 4:8.3.0-1
Debian testing: 4:8.3.0-1
Debian sid: 4:8.3.0-1
Traceback (most recent call last):
        14: from bin/pkg-query:17:in `<main>'
        13: from bin/pkg-query:17:in `each'
        12: from bin/pkg-query:17:in `block in <main>'
        11: from /home/niels/.gem/ruby/2.6.0/gems/pkg-query-0.3/lib/pkg-query.rb:35:in `fedora'
        10: from /home/niels/.gem/ruby/2.6.0/gems/pkg-query-0.3/lib/pkg-query.rb:35:in `new'
         9: from /home/niels/.gem/ruby/2.6.0/gems/watir-6.16.5/lib/watir/browser.rb:46:in `initialize'
         8: from /home/niels/.gem/ruby/2.6.0/gems/selenium-webdriver-3.142.3/lib/selenium/webdriver.rb:88:in `for'
         7: from /home/niels/.gem/ruby/2.6.0/gems/selenium-webdriver-3.142.3/lib/selenium/webdriver/common/driver.rb:46:in `for'
         6: from /home/niels/.gem/ruby/2.6.0/gems/selenium-webdriver-3.142.3/lib/selenium/webdriver/common/driver.rb:46:in `new'
         5: from /home/niels/.gem/ruby/2.6.0/gems/selenium-webdriver-3.142.3/lib/selenium/webdriver/chrome/driver.rb:40:in `initialize'
         4: from /home/niels/.gem/ruby/2.6.0/gems/selenium-webdriver-3.142.3/lib/selenium/webdriver/common/driver.rb:299:in `service_url'
         3: from /home/niels/.gem/ruby/2.6.0/gems/selenium-webdriver-3.142.3/lib/selenium/webdriver/common/service.rb:41:in `chrome'
         2: from /home/niels/.gem/ruby/2.6.0/gems/selenium-webdriver-3.142.3/lib/selenium/webdriver/common/service.rb:41:in `new'
         1: from /home/niels/.gem/ruby/2.6.0/gems/selenium-webdriver-3.142.3/lib/selenium/webdriver/common/service.rb:94:in `initialize'
/home/niels/.gem/ruby/2.6.0/gems/selenium-webdriver-3.142.3/lib/selenium/webdriver/common/service.rb:136:in `binary_path': Unable to find chromedriver. Please download the server from (Selenium::WebDriver::Error::WebDriverError)
https://chromedriver.storage.googleapis.com/index.html and place it somewhere on your PATH.
More info at https://github.com/SeleniumHQ/selenium/wiki/ChromeDriver.
```

What kind of dependency is this one?

**Comment by ablancolopez** [comment]
[ChromeDriver](https://chromedriver.chromium.org/) is a tool for automated tests with web browsers. It allows you to run a web browser "hands-free". It's needed in the query of the Fedora web in order to retrieve the packages info.

I definitely should add more info about it in the readme file.

**Comment by ablancolopez** [comment]
Also, for Arch-based distros, I do believe [this](https://aur.archlinux.org/packages/chromedriver) is the package, though I can't check it as I am running no Arch distro (btw).

Ping me if you install it.
